# Generated by Django 4.0.3 on 2022-06-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventaddress',
            field=models.TextField(),
        ),
    ]
