# Generated by Django 4.0.3 on 2022-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeventApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=122)),
                ('info', models.CharField(max_length=122)),
                ('lang', models.CharField(max_length=122)),
                ('lat', models.CharField(max_length=122)),
            ],
        ),
    ]
