# Generated by Django 4.0.3 on 2022-06-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeventApp', '0002_alter_addevent_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='date',
            field=models.CharField(max_length=122),
        ),
    ]
