# Generated by Django 4.0.3 on 2022-05-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeventApp', '0002_addevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='lang',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='lat',
            field=models.FloatField(),
        ),
    ]
