# Generated by Django 4.0.5 on 2022-06-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeventApp', '0005_alter_event_options_rename_event_make_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Make',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
