# Generated by Django 4.0.6 on 2022-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapeventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='fromtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='todate',
            field=models.CharField(max_length=122),
        ),
    ]
