# Generated by Django 4.0.5 on 2022-06-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapeventApp', '0004_make'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False},
        ),
        migrations.RenameField(
            model_name='make',
            old_name='event',
            new_name='name',
        ),
    ]
